// components/App/Footer.vue
<script setup lang="ts">
const discordModal = ref<HTMLDialogElement | null>(null);
</script>

<template>
    <footer class="w-screen h-40 flex flex-col justify-evenly items-center bg-base-300">
        <div class="flex space-x-4">
            <NuxtLink to="/privacy" class="link link-hover">
                Privacy
            </NuxtLink>
            <NuxtLink to="/contact" class="link link-hover">
                Contact
            </NuxtLink>
            <NuxtLink to="/credits" class="link link-hover">
                Credits
            </NuxtLink>
            <NuxtLink to="https://github.com/6gh/6gh.xyz" class="link link-hover" target="_blank">
                Source Code
                <Icon name="pajamas:external-link" class="inline-block w-4 h-4" />
            </NuxtLink>
        </div>

        <div class="flex space-x-8">
            <NuxtLink to="https://x.com/6ghmid">
                <Icon name="pajamas:x" class="inline-block w-6 h-6" />
            </NuxtLink>
            <NuxtLink to="https://youtube.com/@6gh">
                <Icon name="mdi:youtube" class="inline-block w-7 h-7" />
            </NuxtLink>
            <Icon name="pajamas:discord" class="inline-block w-6 h-6 mt-[2px] cursor-pointer"
                @click="discordModal?.showModal()" />
            <dialog class="modal modal-bottom sm:modal-middle" ref="discordModal">
                <div class="modal-box">
                    <h3 class="font-bold text-lg">Discord Contact</h3>
                    <p class="py-4">My Discord is <span class="font-bold underline">@6gh</span> (or 6gh#7369 for legacy
                        usernames)<br>You are free to DM me and send a friend request at any time.</p>
                    <div class="modal-action">
                        <form method="dialog">
                            <button class="btn">Close</button>
                        </form>
                    </div>
                </div>
            </dialog>
        </div>
    </footer>
</template>

// src/lib/Footer.svelte
<footer class="footer footer-center p-10 bg-base-200 text-base-content rounded mt-auto">
    <div class="grid grid-flow-col gap-4">
        <a href="/contact" class="link link-hover">Contact</a>
        <a href="/credits" class="link link-hover">Credits</a>
        <a href="https://github.com/6gh/6gh.xyz" class="link link-hover">Source Code</a>
    </div>
    <div>
        <div class="grid grid-flow-col gap-4">
            <!-- twitter -->
            <a href="https://twitter.com/6ghmid" target="_blank"
                ><svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    class="fill-current"
                    ><path
                        d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"
                    /></svg
                ></a
            >

            <!-- youtube -->
            <a href="https://www.youtube.com/@6gh" target="_blank"
                ><svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    class="fill-current"
                    ><path
                        d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"
                    /></svg
                ></a
            >

            <!-- discord -->
            <label for="footer-discord" class="link">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    fill="currentColor"
                    class="bi bi-discord"
                    viewBox="0 0 16 16"
                >
                    <path
                        d="M13.545 2.907a13.227 13.227 0 0 0-3.257-1.011.05.05 0 0 0-.052.025c-.141.25-.297.577-.406.833a12.19 12.19 0 0 0-3.658 0 8.258 8.258 0 0 0-.412-.833.051.051 0 0 0-.052-.025c-1.125.194-2.22.534-3.257 1.011a.041.041 0 0 0-.021.018C.356 6.024-.213 9.047.066 12.032c.001.014.01.028.021.037a13.276 13.276 0 0 0 3.995 2.02.05.05 0 0 0 .056-.019c.308-.42.582-.863.818-1.329a.05.05 0 0 0-.01-.059.051.051 0 0 0-.018-.011 8.875 8.875 0 0 1-1.248-.595.05.05 0 0 1-.02-.066.051.051 0 0 1 .015-.019c.084-.063.168-.129.248-.195a.05.05 0 0 1 .051-.007c2.619 1.196 5.454 1.196 8.041 0a.052.052 0 0 1 .053.007c.08.066.164.132.248.195a.051.051 0 0 1-.004.085 8.254 8.254 0 0 1-1.249.594.05.05 0 0 0-.03.03.052.052 0 0 0 .003.041c.24.465.515.909.817 1.329a.05.05 0 0 0 .056.019 13.235 13.235 0 0 0 4.001-2.02.049.049 0 0 0 .021-.037c.334-3.451-.559-6.449-2.366-9.106a.034.034 0 0 0-.02-.019Zm-8.198 7.307c-.789 0-1.438-.724-1.438-1.612 0-.889.637-1.613 1.438-1.613.807 0 1.45.73 1.438 1.613 0 .888-.637 1.612-1.438 1.612Zm5.316 0c-.788 0-1.438-.724-1.438-1.612 0-.889.637-1.613 1.438-1.613.807 0 1.451.73 1.438 1.613 0 .888-.631 1.612-1.438 1.612Z"
                    />
                </svg>
            </label>

            <input type="checkbox" id="footer-discord" class="modal-toggle" />
            <div class="modal modal-bottom sm:modal-middle">
                <div class="modal-box">
                    <h3 class="font-bold text-lg">Contact me via Discord</h3>
                    <p class="py-4">
                        You may contact me via Discord. Just send me a Friend Request or Direct
                        Message at <span class="font-bold underline">6gh#7369</span>.
                    </p>
                    <div class="modal-action">
                        <label for="footer-discord" class="btn">Close</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <p>Copyright © 2023 - All right reserved by 6gh</p>
    </div>
</footer>
